const state={data:null,media:null,projectIndex:0,activeGroup:'全部',lightboxItems:[],lightboxIndex:0,touchStartX:0};
const $=s=>document.querySelector(s);
async function load(){const [data,media]=window.PORTFOLIO_DATA&&window.MEDIA_MAP?[window.PORTFOLIO_DATA,window.MEDIA_MAP]:await Promise.all([fetch('data/portfolio-data.json',{cache:'no-store'}).then(r=>r.json()),fetch('data/media-map.json',{cache:'no-store'}).then(r=>r.json())]);const agentIndex=data.projects.findIndex(p=>p.id==='image-agent');if(agentIndex>0)data.projects.unshift(data.projects.splice(agentIndex,1)[0]);state.data=data;state.media=media;render();}
function render(){renderAgentImpact();renderIpImpact();renderMultiProjectImpact();renderMetrics();renderProjects();renderLoops();renderFuturePlans();renderPlatforms();}
function renderAgentImpact(){const a=state.data.imageAgentImpact,max=Math.max(...a.ranking.map(x=>x.count));$('#agent-impact-panel').innerHTML=`<div class="agent-impact-head"><div><p class="agent-impact-kicker">CORE RESULT · IMAGE AGENT</p><h3>${a.question}</h3><p>${a.conclusion}</p></div><span>${a.period}</span></div><div class="agent-impact-stats"><div><strong>${a.users}</strong><span>使用人数</span></div><div><strong>${a.nonDesignerUsers}</strong><span>非设计师 · ${a.nonDesignerShare}</span></div><div><strong>${a.generatedImages}</strong><span>生成图片</span></div><div><strong>${a.servicePackages}</strong><span>支持服务包</span></div></div><div class="agent-impact-body"><div><h4>用户生成量排名</h4><div class="agent-ranking">${a.ranking.map(x=>`<div class="agent-rank-row"><span>${x.rank}</span><b>${x.name}</b><i><em style="width:${x.count/max*100}%"></em></i><strong>${x.count} 张</strong></div>`).join('')}</div></div><aside><h4>业务验证结论</h4><ul><li><b>85.7%</b> 使用者为非设计师，证明工具有效降低专业门槛。</li><li><b>504 张</b> 实际输出，证明平台已被持续使用而非停留在演示阶段。</li><li><b>71 个服务包</b> 获得生产支持，Agent 已进入业务交付链路。</li><li>前三名合计 <b>258 张，占总量 51.2%</b>，已形成核心高频用户。</li></ul><p class="agent-data-note">${a.dataNote}</p></aside></div>`}
function renderIpImpact(){const a=state.data.ipServicePackImpact;$('#ip-impact-panel').innerHTML=`<div class="ip-impact-head"><div><p class="ip-impact-kicker">SECOND CORE RESULT · IP SERVICE PACK</p><h3>${a.question}</h3><p>${a.conclusion}</p></div><span>${a.processStatus}</span></div><div class="ip-impact-stats"><div><strong>${a.packageCount}</strong><span>IP服务包</span></div><div><strong>${a.teamSize}</strong><span>人完成全流程</span></div><div><strong>${a.offlineCycle}</strong><span>线下物料周期难点</span></div><div><strong>6</strong><span>关键生产环节</span></div></div><div class="ip-stages">${a.stages.map((x,i)=>`<div><b>${String(i+1).padStart(2,'0')}</b><span>${x}</span></div>`).join('')}</div><div class="ip-flow-compare"><section><h4>原流程 · 串行等待</h4>${a.oldFlow.map(x=>`<span>${x}</span>`).join('')}</section><section class="new-flow"><h4>新流程 · 前置储备与并行生产</h4>${a.newFlow.map(x=>`<span>${x}</span>`).join('')}</section></div><div class="ip-theme-list"><b>已跑通的7个IP主题</b>${a.themes.map(x=>`<span>${x}</span>`).join('')}</div>`}
function renderMultiProjectImpact(){const a=state.data.multiProjectImpact;$('#multi-project-impact-panel').innerHTML=`<div class="multi-impact-head"><div><p class="multi-impact-kicker">THIRD CORE RESULT · PARALLEL DELIVERY</p><h3>${a.question}</h3><p>${a.conclusion}</p></div><span>${a.managementStatus}</span></div><div class="multi-impact-summary"><div><strong>${a.projectCount}</strong><span>条项目线同步推进</span></div><div><strong>${a.workTypes}</strong><span>类工作协同管理</span></div><div><strong>1</strong><span>套统一管理节奏</span></div><p>${a.period}</p></div><div class="parallel-projects"><div class="parallel-axis"><span>同一周期启动</span><i></i><span>持续并行交付</span></div>${a.projects.map((x,i)=>`<div class="parallel-row"><b>${String(i+1).padStart(2,'0')}</b><div><strong>${x.name}</strong><span>${x.type}</span></div><i><em style="--delay:${i%3}"></em></i><p>${x.output}</p></div>`).join('')}</div><div class="multi-management"><section><h4>时间与项目管理方法</h4><div class="management-flow">${a.managementFlow.map((x,i)=>`<span><b>${String(i+1).padStart(2,'0')}</b>${x}</span>`).join('')}</div></section><aside><h4>协同能力体现</h4><ul>${a.managementValue.map(x=>`<li>${x}</li>`).join('')}</ul></aside></div>`}
function renderMetrics(){
  $('#metric-grid').innerHTML=state.data.dashboard.metrics.map(m=>`<article class="metric-card"><div class="metric-value">${m.value}</div><div class="metric-label">${m.label}</div><div class="metric-note">${m.note}</div></article>`).join('');
  const rows=state.data.servicePackage.assistedProducts; const max=Math.max(...rows.map(x=>x.useCount));
  $('#package-bars').innerHTML=rows.map(x=>`<div class="bar-row"><span>${x.name}</span><div class="bar-track"><div class="bar-fill" style="width:${x.useCount/max*100}%"></div></div><strong>${x.useCount.toLocaleString()} 次</strong></div>`).join('');
}
function renderProjects(){
  $('#project-tabs').innerHTML=state.data.projects.map((p,i)=>`<button class="tab ${i===state.projectIndex?'active':''}" data-index="${i}" role="tab">${p.shortTitle}</button>`).join('');
  document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{state.projectIndex=+b.dataset.index;state.activeGroup='全部';renderProjects()});
  renderProjectView();
}
function mediaFor(id){return state.media.projects.find(p=>p.projectId===id)?.items||[]}
function countLabel(items){const images=items.filter(x=>x.type==='image').length,videos=items.filter(x=>x.type==='video').length;if(images&&videos)return `${items.length}项`;if(videos)return `${videos}条`;return `${images}张`}
function renderProjectView(){
  const p=state.data.projects[state.projectIndex],items=mediaFor(p.id),groups=[...new Set(items.map(x=>x.group||'项目素材'))];
  if(state.activeGroup!=='全部'&&!groups.includes(state.activeGroup))state.activeGroup='全部';
  const filtered=state.activeGroup==='全部'?items:items.filter(x=>(x.group||'项目素材')===state.activeGroup);
  const filters=items.length?`<div class="gallery-filters" aria-label="素材分类筛选"><button class="filter-button ${state.activeGroup==='全部'?'active':''}" data-group="全部">全部（${countLabel(items)}）</button>${groups.map(g=>{const gi=items.filter(x=>(x.group||'项目素材')===g);return `<button class="filter-button ${state.activeGroup===g?'active':''}" data-group="${g}">${g}（${countLabel(gi)}）</button>`}).join('')}</div>`:'';
  const cards=filtered.length?filtered.map((x,i)=>x.type==='video'?`<article class="media-card video-card"><div class="media-frame"><video controls preload="metadata" src="${x.src}" aria-label="${x.title}"></video></div><h5>${x.title}</h5><p>${x.caption||''}</p></article>`:`<button class="media-card image-card" data-image-index="${i}" aria-label="放大查看：${x.title}"><span class="media-frame"><img src="${x.src}" alt="${x.title}" loading="lazy"></span><span class="media-title">${x.title}</span><span class="media-description">${x.caption||''}</span></button>`).join(''):`<div class="placeholder">该分类暂时没有素材。</div>`;
  $('#project-view').innerHTML=`<div class="project-title-row"><div><h3>${p.title}</h3><p class="project-summary">${p.summary}</p></div><span class="status">${p.status}</span></div><section class="media-gallery">${filters}<div class="gallery-heading"><h4>${state.activeGroup}（${countLabel(filtered)}）</h4></div><div class="media-grid">${cards}</div></section><div class="project-details"><div class="detail-box"><strong>业务问题</strong><p>${p.problem}</p></div><div class="detail-box"><strong>核心行动</strong><p>${p.action}</p></div><div class="detail-box"><strong>结果 / 证据</strong><p>${p.result}</p></div></div>`;
  document.querySelectorAll('.filter-button').forEach(b=>b.onclick=()=>{state.activeGroup=b.dataset.group;renderProjectView()});
  state.lightboxItems=filtered.filter(x=>x.type==='image');
  document.querySelectorAll('[data-image-index]').forEach(b=>{const item=filtered[+b.dataset.imageIndex];b.onclick=()=>openLightbox(item,state.lightboxItems.indexOf(item))});
}
function openLightbox(item,index){state.lightboxIndex=index;updateLightbox();$('#lightbox').showModal()}
function updateLightbox(){const item=state.lightboxItems[state.lightboxIndex];if(!item)return;$('#lightbox-image').src=item.src;$('#lightbox-image').alt=item.title;$('#lightbox-caption').textContent=`${state.lightboxIndex+1} / ${state.lightboxItems.length} · ${item.caption||item.title}`}
function moveLightbox(delta){const len=state.lightboxItems.length;if(!len)return;state.lightboxIndex=(state.lightboxIndex+delta+len)%len;updateLightbox()}
$('#lightbox-close').onclick=()=>$('#lightbox').close();
$('#lightbox-prev').onclick=()=>moveLightbox(-1);
$('#lightbox-next').onclick=()=>moveLightbox(1);
$('#lightbox').addEventListener('keydown',e=>{if(e.key==='ArrowLeft')moveLightbox(-1);if(e.key==='ArrowRight')moveLightbox(1)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#lightbox').open)$('#lightbox').close()});
$('#lightbox').addEventListener('touchstart',e=>{state.touchStartX=e.changedTouches[0].screenX},{passive:true});
$('#lightbox').addEventListener('touchend',e=>{const dx=e.changedTouches[0].screenX-state.touchStartX;if(Math.abs(dx)>50)moveLightbox(dx>0?-1:1)},{passive:true});
function renderLoops(){const steps=state.data.businessLoop;$('#loop-flow').innerHTML=steps.map((s,i)=>`<div class="loop-step">${String(i+1).padStart(2,'0')}<br>${s}</div>`).join('');$('#project-loops').innerHTML=state.data.projects.slice(0,4).map(p=>`<article class="loop-card"><h3>${p.shortTitle}</h3><dl><dt>问题</dt><dd>${p.problem}</dd><dt>行动</dt><dd>${p.action}</dd><dt>结果</dt><dd>${p.result}</dd><dt>下一步</dt><dd>${p.next}</dd></dl></article>`).join('')}
function renderFuturePlans(){$('#future-plan-grid').innerHTML=state.data.futurePlans.map((p,i)=>`<article class="future-plan-card"><div class="future-plan-number">0${i+1}</div><p class="future-plan-type">${p.type}</p><h3>${p.title}</h3><p class="future-plan-summary">${p.summary}</p>${p.link?`<a class="future-plan-link" href="${p.link}" target="_blank" rel="noopener noreferrer">${p.linkLabel||'查看相关资料'} ↗</a>`:''}${p.projectTarget?`<a class="future-plan-link" href="#gallery" data-project-target="${p.projectTarget}">${p.projectLinkLabel||'查看对应项目'} ↓</a>`:''}${p.image?`<figure class="future-plan-visual"><img src="${p.image}" alt="${p.imageAlt||p.title}" loading="lazy"></figure>`:''}${p.basis?`<div class="future-plan-block plan-basis"><strong>方案依据</strong><p>${p.basis}</p></div>`:''}<div class="future-plan-block"><strong>协作与输入</strong><p>${p.input}</p></div><div class="future-plan-block"><strong>重点行动</strong><ul>${p.actions.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="future-plan-block"><strong>目标闭环</strong><p>${p.loop}</p></div>${p.channels?`<div class="channel-list">${p.channels.map(x=>`<span>${x}</span>`).join('')}</div>`:''}</article>`).join('');document.querySelectorAll('[data-project-target]').forEach(a=>a.onclick=()=>{const i=state.data.projects.findIndex(p=>p.id===a.dataset.projectTarget);if(i>=0){state.projectIndex=i;state.activeGroup='全部';renderProjects()}})}
function renderPlatforms(){$('#platform-grid').innerHTML=state.data.platforms.map(p=>`<article class="platform-card"><span class="status">${p.status}</span><h3>${p.name}</h3><p>${p.summary}</p><p>${p.accessNote}</p><a href="${p.url}" target="_blank" rel="noreferrer">打开平台 ↗</a></article>`).join('')}
load().catch(e=>{$('main').innerHTML=`<section class="section"><h1>需要通过本地服务器预览</h1><p>运行 README 中的一行命令即可。错误：${e.message}</p></section>`});
